### ISSUE TITLE
can you help me? I have tried to reforge colored_lights_core 1.7.10

### ISSUE THREAD

**Issue by ff6f8d68** [danderfer/Comp_Sci_Sem_2#7]
Prism Launcher version: 7.2 (official)

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.64.103.92, 18.64.103.101, 18.64.103.51, 18.64.103.80]

session.minecraft.net resolves to:
    [13.107.213.45, 13.107.246.45]

textures.minecraft.net resolves to:
    [13.107.213.45, 13.107.246.45]

api.mojang.com resolves to:
    [13.107.246.45, 13.107.213.45]

Minecraft folder is:
/Users/atom20003113/Library/Application Support/PrismLauncher/instances/istacesdata/clightscore test/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java

Java is version 17.0.8, using 64 (aarch64) architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /Users/atom20003113/Library/Application Support/PrismLauncher/instances/istacesdata/clightscore test/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-macos-arm64/3.3.1/lwjgl-glfw-natives-macos-arm64-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-macos-arm64/3.3.1/lwjgl-jemalloc-natives-macos-arm64-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-macos-arm64/3.3.1/lwjgl-natives-macos-arm64-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-macos-arm64/3.3.1/lwjgl-openal-natives-macos-arm64-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-macos-arm64/3.3.1/lwjgl-opengl-natives-macos-arm64-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-macos-arm64/3.3.1/lwjgl-stb-natives-macos-arm64-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-macos-arm64/3.3.1/lwjgl-tinyfd-natives-macos-arm64-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/ca/weblite/java-objc-bridge/1.1/java-objc-bridge-1.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.6-prism/ForgeWrapper-1.5.6-prism.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/cpw/mods/securejarhandler/2.1.6/securejarhandler-2.1.6.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/forgespi/7.0.0/forgespi-7.0.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/net/minecraftforge/fmlloader/1.20-46.0.14/fmlloader-1.20-46.0.14.jar
  /Users/atom20003113/Library/Application Support/PrismLauncher/libraries/com/mojang/minecraft/1.20/minecraft-1.20-client.jar

Native libraries:

Mods:
  [✔] ColoredLightsCore-1.3.7.39

Params:
  --username  --version 1.20 --gameDir /Users/atom20003113/Library/Application Support/PrismLauncher/instances/istacesdata/clightscore test/.minecraft --assetsDir /Users/atom20003113/Library/Application Support/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 46.0.14 --fml.mcVersion 1.20 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230608.053357

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="Prism Launcher: clightscore test", -XstartOnFirstThread, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 1240

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-10-23 18:59:50,682 main WARN Advanced terminal features are not available in this environment
[18:59:50] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, atom20003113, --version, 1.20, --gameDir, /Users/atom20003113/Library/Application Support/PrismLauncher/instances/istacesdata/clightscore test/.minecraft, --assetsDir, /Users/atom20003113/Library/Application Support/PrismLauncher/assets, --assetIndex, 5, --uuid, &lt;PROFIL-ID&gt;, --accessToken, ❄❄❄❄❄❄❄❄, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 46.0.14, --fml.mcVersion, 1.20, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230608.053357, --width, 854, --height, 480]
[18:59:50] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.8 by Oracle Corporation; OS Mac OS X arch aarch64 version 14.0
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.IllegalArgumentException: ColoredLightsCore-1.3.7.39 Kopie.coloredlightscore.src.asm.transformer.core: Invalid package name: 'ColoredLightsCore-1' is not a Java identifier
	at java.base/jdk.internal.module.Checks.requireTypeName(Checks.java:154)
	at java.base/jdk.internal.module.Checks.requirePackageName(Checks.java:72)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.lang.module.ModuleDescriptor$Builder.packages(ModuleDescriptor.java:2026)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.SimpleJarMetadata.descriptor(SimpleJarMetadata.java:16)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:51)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar$JarModuleDataProvider.descriptor(Jar.java:276)
	at MC-BOOTSTRAP/fmlloader@1.20-46.0.14/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:62)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at MC-BOOTSTRAP/fmlloader@1.20-46.0.14/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:50)
	at MC-BOOTSTRAP/fmlloader@1.20-46.0.14/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:33)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService.candidates(ITransformerDiscoveryService.java:48)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Der Prozess wurde mit Status 2 beendet.

**Comment by ff6f8d68** [comment]
[ColoredLightsCore-1.zip](https://github.com/danderfer/Comp_Sci_Sem_2/files/13074034/ColoredLightsCore-1.zip)
the mod files
